# Generated by Django 2.2.5 on 2019-10-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_img',
        ),
    ]
