# Generated by Django 2.2.6 on 2019-10-08 14:26

from django.db import migrations, models
import main.system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_like_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_url',
            field=models.ImageField(storage=main.system.storage.ImageStorage(), upload_to='img'),
        ),
    ]
