# Generated by Django 2.2.6 on 2019-10-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191008_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='computerScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
