# Generated by Django 2.2.6 on 2019-10-15 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20191015_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commend',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commend_id',
            new_name='comment_id',
        ),
    ]
