# Generated by Django 2.2.6 on 2019-10-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191015_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
