# Generated by Django 2.2.6 on 2019-10-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191016_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Img'),
        ),
    ]
